{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  instances: {{ .Values.postgres.instances }}
  
  postgresql:
    parameters:
      max_connections: {{ .Values.postgres.postgresql.maxConnections | quote }}
      shared_buffers: {{ .Values.postgres.postgresql.sharedBuffers | quote }}
  
  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.owner }}
  
  storage:
    size: {{ .Values.postgres.storage.size }}
    storageClass: {{ .Values.postgres.storage.storageClass }}
  
  resources:
    requests:
      memory: {{ .Values.postgres.resources.requests.memory | quote }}
      cpu: {{ .Values.postgres.resources.requests.cpu | quote }}
    limits:
      memory: {{ .Values.postgres.resources.limits.memory | quote }}
      cpu: {{ .Values.postgres.resources.limits.cpu | quote }}
  
  {{- if .Values.postgres.affinity.enabled }}
  affinity:
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  {{- end }}
{{- end }}
